[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
adsampling = { path = "../adsampling" }
diskann = { path = "../diskann" }
platform = { path = "../platform" }
orion = { path = "../orion" }
vector = { path = "../vector" }
anyhow = "1"
rayon = { workspace = true }
ndarray = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
byteorder = { workspace = true }
indicatif = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
comfy-table = { workspace = true }
serde_yaml = "0.9"
