[package]
name = "hnsw"
version = "0.1.0"
edition = "2021"

[dependencies]
vector = { path = "../vector" }
platform = { path = "../platform" }
rayon = { workspace = true }
rand = { workspace = true }
crossbeam = { workspace = true }
hashbrown = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
byteorder = { workspace = true }
memmap2 = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
