[package]
name = "ssd_diskann"
version = "0.1.0"
edition = "2021"

[dependencies]
diskann = { path = "../diskann" }
platform = { path = "../platform" }
vector = { path = "../vector" }
staged_diskann = { path = "../staged_diskann" }
byteorder = { workspace = true }
memmap2 = { workspace = true }
hashbrown = { workspace = true }
ndarray = { workspace = true }
log = { workspace = true }
anyhow = "1"
rayon = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
