[package]
name = "platform"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = { workspace = true }
libc = { workspace = true }
crossbeam = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
vector = { path = "../vector" }
once_cell = { workspace = true }


[dev-dependencies]
approx = "0.5"